#!/usr/bin/env bash
#

n=1

while [ $n -le 100 ]

do
	if [ $((n%3)) == 0 ]
        then
                echo "Fizz"

        fi

        if [ $((n%5)) == 0 ]
        then
                echo "Buzz"
        fi

        echo "$n"
        ((n++))
done
