#!/usr/bin/env bash
#

case=0

while [ $case -lt 20 ]

do
	if [ $case -eq 3 ]
	then
		echo "bad luck from China"
	elif [ $case -eq 8 ]
	then
		echo "bad luck from Japan"
	elif [ $case -eq 16 ]
	then
		echo "bad luck from Italy"
	else
		(( case++ ))
	fi
done
