#!/usr/bin/env bash
#

i=0

while [ $i -lt 20 ] ;

do
	case in $i
		3)
			echo "bad luck from China"
			;;
		2)
			echo "bad luck from Japan"
			;;
		3)
			echo "bad luck from Italy"
			;;
	esac
done

