#!/usr/bin/env bash
#

case=0

while [ $case -lt 20 ]

do
	if [ $case -eq 3 ]
	then
		echo "bad luck from China"
	elif [ $case -eq 8 ]
	then
		echo "bad luck from Japan"
	else [ $case -eq 16 ]
		echo "bad luck from Italy"
	fi
	(( case++ ))
done
