#!/usr/bin/env bash
#
school=""

if [ $school -eq -e ]
	echo "school file exists"

	if [ $school -ne -s ]
		echo "school file is emply"
		
		if [ $school -eq -f ]
			echo "school is a regular file"
		
	else
		echo "school file is not emply"
else
	echo "school file does not exist"
	




 	
