#!/usr/bin/env bash
#
school=""

if [ $school -eq -e ]
	echo "school file exists"
		elif [ $school -ne -s ]
                	echo "school file is emply"

                elif [ $school -eq -f ]
                        echo "school is a regular file"

        elif
                echo "school file is not emply"
else
	echo "school file does not exist"
	




 	
