#!/usr/bin/env bash
#
mkdir /var/run/myscript.pid >> ps

i=1

while [ $i -eq 0 ]
do

	trap " echo I hate the kill command " SIGTERM
	trap " echo Y U no love me?! " SIGINT
	echo " To infinity and beyond"
	((i++))

done

